services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: SUA_SENHA_ROOT
      MYSQL_DATABASE: SEU_BANCO
      MYSQL_USER: SEU_USUARIO
      MYSQL_PASSWORD: SUA_SENHA
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - AutoMarkNet

  app:
    image: peniel-bike-img
    container_name: peniel-bike-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings:DefaultConnection=Server=db;Database=SEU_BANCO;User=SEU_USUARIO;Password=SUA_SENHA;
    depends_on:
      - db
    networks:
      - AutoMarkNet

volumes:
  mysql-data:

networks:
  AutoMarkNet:
    name: AutoMarkNet
    external: true